/**
 * Verify JS CNN inference matches Python predictions.
 * Loads test_vectors.json (generated by Python) and compares.
 */

import { readFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { classifyWindow, normalizeFeatures } from "./classify_cnn.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const vectors = JSON.parse(readFileSync(join(__dirname, "test_vectors.json"), "utf-8"));

let maxDiff = 0;
let failures = 0;
const diffs = [];

for (let i = 0; i < vectors.length; i++) {
  const v = vectors[i];

  // Normalize continuous features
  const normalizedCont = v.cont.map(row => normalizeFeatures(row));

  const { score } = classifyWindow(v.cat, normalizedCont, v.win);
  const diff = Math.abs(score - v.python_score);

  diffs.push(diff);
  if (diff > maxDiff) maxDiff = diff;
  if (diff > 1e-4) {
    failures++;
    if (failures <= 5) {
      console.log(`  MISMATCH [${i}]: JS=${score.toFixed(6)} Python=${v.python_score.toFixed(6)} diff=${diff.toExponential(2)} label=${v.label}`);
    }
  }
}

const avgDiff = diffs.reduce((a, b) => a + b, 0) / diffs.length;
console.log(`\nParity check: ${vectors.length} test vectors`);
console.log(`  Max diff:  ${maxDiff.toExponential(3)}`);
console.log(`  Avg diff:  ${avgDiff.toExponential(3)}`);
console.log(`  Failures (diff > 1e-4): ${failures}`);
console.log(`  Status: ${failures === 0 ? "PASS" : "FAIL"}`);

// Also check label agreement
let labelAgree = 0;
const threshold = 0.60;
for (const v of vectors) {
  const { score } = classifyWindow(v.cat, v.cont.map(row => normalizeFeatures(row)), v.win);
  const jsStuck = score >= threshold;
  const pyStuck = v.python_score >= threshold;
  if (jsStuck === pyStuck) labelAgree++;
}
console.log(`  Label agreement at t=0.60: ${labelAgree}/${vectors.length}`);
